version: "3.4"

services:
  gooutsafe:
    image: gooutsafe/entrypoint:latest
    deploy:
      restart_policy:
        condition: on-failure
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - database
      - redis
    ports:
      - 5000:5000
    env_file:
      - .env.docker
    volumes:
      - type: bind
        source: ./monolith/
        target: /home/gooutsafe/monolith/

  # GATEWAYS

  api-gateway:
    image: gooutsafe/api-gateway:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - user-service
      - restaurant-service
      - booking-service
    expose:
      - "5000"

  # SERVICES

  user-service:
    image: gooutsafe/user-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - user-service-db
      - restaurant-service
    expose:
      - "5000"
    env_file:
      - .env.docker
    environment:
      - DATABASE_URI=mysql+pymysql://gooutsafe:my-secret-pw@user-service-db/gooutsafe

  restaurant-service:
    image: gooutsafe/restaurant-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - restaurant-service-db
    expose:
      - "5000"
    env_file:
      - .env.docker
    environment:
      - DATABASE_URI=mysql+pymysql://gooutsafe:my-secret-pw@restaurant-service-db/gooutsafe

  booking-service:
    image: gooutsafe/booking-service:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - booking-service-db
      - restaurant-service
    env_file:
      - .env.docker
    expose:
      - "5000"
    environment:
      - DATABASE_URI=mysql+pymysql://gooutsafe:my-secret-pw@booking-service-db/gooutsafe

  # THIRD-PARTY SERVICES

  elastic-search:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.10.0"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
      - "9300"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]

  celery-service:
    image: gooutsafe/celery-service:latest
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - "restaurant-service"
    expose:
      - "5000"
    env_file:
      - .env.docker

  redis:
    image: "redis:6.0.8-alpine"
    deploy:
      restart_policy:
        condition: on-failure
    expose:
      - "6379"

  # DATABASES

  database:
    image: "mysql:8"
    deploy:
      restart_policy:
        condition: on-failure
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    volumes:
      - database-data:/var/lib/mysql
    env_file:
      - .env.docker

  user-service-db:
    image: "mysql:8"
    deploy:
      restart_policy:
        condition: on-failure
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    volumes:
      - user-service-data:/var/lib/mysql
    env_file:
      - .env.docker

  restaurant-service-db:
    image: "mysql:8"
    deploy:
      restart_policy:
        condition: on-failure
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    volumes:
      - restaurant-service-data:/var/lib/mysql
    env_file:
      - .env.docker

  booking-service-db:
    image: "mysql:8"
    deploy:
      restart_policy:
        condition: on-failure
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    volumes:
      - booking-service-data:/var/lib/mysql
    env_file:
      - .env.docker

volumes:
  database-data:
  user-service-data:
  restaurant-service-data:
  booking-service-data:
