name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
      - name: Assign issues with `priority 1` label to project Priority 1
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          contains(github.event.issue.labels.*.name, 'priority 1')
        with:
          project: "https://github.com/reuseman/GoOutSafe/projects/1"
          column_name: "To do"
      - name: Assign issues with `priority 2` label to project Priority 2
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          contains(github.event.issue.labels.*.name, 'priority 2')
        with:
          project: "https://github.com/reuseman/GoOutSafe/projects/2"
          column_name: "To do"
      - name: Assign issues with `priority 3` label to project Priority 3
        uses: srggrs/assign-one-project-github-action@1.2.0
        if: |
          contains(github.event.issue.labels.*.name, 'priority 3')
        with:
          project: "https://github.com/reuseman/GoOutSafe/projects/3"
          column_name: "To do"
